diff --git a/destroyall/Makefile b/destroyall/Makefile
updated copyright

updated to version 0.4

diff --git a/destroyall/destroyall.cpp b/destroyall/destroyall.cpp

added xattr, chmod and sudo (force)

diff --git a/findexts/Makefile b/findexts/Makefile

fixed reference to stringlib

diff --git a/findexts/findexts.cpp b/findexts/findexts.cpp

updated date

diff --git a/go-multiren/build b/go-multiren/build

removed -s for compatibility

added build and test system

diff --git a/go-multiren/multiren.go b/go-multiren/multiren.go

added permissions normalization
shortmonthname to digits
pad day with 0's

+func NormalizePermissions(filename string, force bool) {
+//ShortMonthNametoDigits : change short month to padded number
+func ShortMonthNametoDigits(m string) string {
+//PadDay : add a zero to days 1 through 9
+func PadDay(d string) string {

correctly parse ".tar.bz2"

only modtime if redate is enabled

only add date if adddate is enabled

diff --git a/norepeats/norepeats.cpp b/norepeats/norepeats.cpp

added option to look at only files 1GB and less

removed 'load from cache' option

added force (adds sudo) option

diff --git a/nospaces/nospaces.cpp b/nospaces/nospaces.cpp

added force option and permissions

added option to undo space-removal

diff --git a/stringsfltr/stringsfltr.cpp b/stringsfltr/stringsfltr.cpp

filter for strings utility

detect possible virus

diff --git a/go-multiren/build b/go-multiren/build
--- a/go-multiren/build
+++ b/go-multiren/build
@@ -15,7 +15,7 @@ fi
 
 
 if [ "$1" == "-install" ]; then
-	sudo install -v -s -m 755 $EXE $INSTALLDIR
+	sudo install -v -m 755 $EXE $INSTALLDIR
 	which $EXE
 	$EXE -version
 	exit 0
@@ -91,7 +91,81 @@ if [ "$1" == "-test" ]; then
 	fi
 	gecho 
 	gecho "====== clean up ======"
-	rm -vf ${TESTFILE_JUSTFILE_NOSPACES}${MODDATE}.${TESTFILE_EXT}
-	rmdir -p ${TESTPATH}
+	sudo rm -vf ${TESTFILE_JUSTFILE_NOSPACES}${MODDATE}.${TESTFILE_EXT}
+	sudo rmdir -p ${TESTPATH}
+	 #./multiren -filename "localtextfile.txt" -newpath path/to/new/location -verbose -force -redate 01Jan1980
+	gecho "====== TEST 4: force an alternate date ======"
+
+	MODDATE="01Jan1980"
+	gecho "./$EXE -filename \"${TESTFILE_JUSTFILE}.${TESTFILE_EXT}\"  -verbose -force -redate ${MODDATE} | sh"
+	
+	touch "${TESTFILE_JUSTFILE}.${TESTFILE_EXT}"
+	./$EXE -filename "${TESTFILE_JUSTFILE}.${TESTFILE_EXT}" -verbose -force -redate ${MODDATE} | sh
+
+	gecho -e "if [ -e \"./${TESTFILE_JUSTFILE}-${MODDATE}.${TESTFILE_EXT}\" ]; then (we good)"
+	if [ -e "./${TESTFILE_JUSTFILE}-${MODDATE}.${TESTFILE_EXT}" ]; then
+			echo "passing test 4"
+	else
+			echo "failed on test 4"
+			exit 1
+	fi
+	gecho
+
+	gecho "====== clean up ======"
+	rm -vf ${TESTFILE_JUSTFILE}-${MODDATE}.${TESTFILE_EXT}
+
+
+	gecho "====== TEST 5: source file in relative subdirectory ======"
+
+	mkdir -p subdir1/subdir2/subdir3
+	mkdir -p tgtdir1/tgtdir2/tgtdir3
+	touch "subdir1/subdir2/subdir3/${TESTFILE_JUSTFILE}.${TESTFILE_EXT}"
+
+	gecho "./$EXE -filename \"subdir1/subdir2/subdir3/${TESTFILE_JUSTFILE}.${TESTFILE_EXT}\"  -newpath \"tgtdir1/tgtdir2/tgtdir3/\" -verbose -skipdate | sh"
+	./$EXE -filename "subdir1/subdir2/subdir3/localtextfile.txt"  -newpath "tgtdir1/tgtdir2/tgtdir3/" -verbose -skipdate | sh
+
+	gecho -e "if [ -e \"tgtdir1/tgtdir2/tgtdir3/${TESTFILE_JUSTFILE}.${TESTFILE_EXT}\" ]; then (we good)"
+	
+	if [ -e "tgtdir1/tgtdir2/tgtdir3/${TESTFILE_JUSTFILE}.${TESTFILE_EXT}" ]; then
+			echo "passing test 5"
+	else
+			echo "failed on test 5"
+			exit 1
+	fi
+	gecho
+
+	gecho "====== clean up ======"
+	rm -vf tgtdir1/tgtdir2/tgtdir3/${TESTFILE_JUSTFILE}.${TESTFILE_EXT}
+	rmdir -p tgtdir1/tgtdir2/tgtdir3
+	rmdir -p subdir1/subdir2/subdir3
+
+	gecho "====== TEST 6: source file in relative subdirectory + redate ======"
+
+	mkdir -p subdir1/subdir2/subdir3
+	mkdir -p tgtdir1/tgtdir2/tgtdir3
+	touch "subdir1/subdir2/subdir3/${TESTFILE_JUSTFILE}.${TESTFILE_EXT}"
+
+	gecho "./$EXE -filename \"subdir1/subdir2/subdir3/${TESTFILE_JUSTFILE}.${TESTFILE_EXT}\"  -newpath \"tgtdir1/tgtdir2/tgtdir3/\" -verbose -redate ${MODDATE} | sh"
+	./$EXE -filename "subdir1/subdir2/subdir3/localtextfile.txt"  -newpath "tgtdir1/tgtdir2/tgtdir3/" -verbose -redate ${MODDATE} | sh
+
+	gecho -e "if [ -e \"tgtdir1/tgtdir2/tgtdir3/${TESTFILE_JUSTFILE}-${MODDATE}.${TESTFILE_EXT}\" ]; then (we good)"
+	
+	if [ -e "tgtdir1/tgtdir2/tgtdir3/${TESTFILE_JUSTFILE}-${MODDATE}.${TESTFILE_EXT}" ]; then
+			echo "passing test 6"
+	else
+			echo "failed on test 6"
+			exit 1
+	fi
+	gecho
+
+	gecho "====== clean up ======"
+	rm -vf tgtdir1/tgtdir2/tgtdir3/${TESTFILE_JUSTFILE}-${MODDATE}.${TESTFILE_EXT}
+	rmdir -p tgtdir1/tgtdir2/tgtdir3
+	rmdir -p subdir1/subdir2/subdir3
+
+
+
+	
+
 	gecho "====== All tests passing ======"
 fi
